language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jagiello95/test-aws-ci-cd -f Dockerfile.dev .

script:
  - docker run -e CI=true jagiello95/test-aws-ci-cd npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "test-aws-ci-cd"
  env: "Testawscicd-env"
  bucket_name: "elasticbeanstalk-us-east-2-441340877932"
  bucket_path: "test-aws-ci-cd"
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master